import { Faction } from "../types/matchupGeneratorTypes";

export const factions: Faction[] = [
    { name: "Ardiaei", type: "greek", torts_enabled: false },
    { name: "Arevaci", type: "barb", torts_enabled: false },
    { name: "Armenia", type: "sally", torts_enabled: false },
    { name: "Arverni", type: "barb", torts_enabled: false },
    { name: "Athens", type: "greek", torts_enabled: true },
    { name: "Baktria", type: "greek", torts_enabled: false },
    { name: "Boii", type: "barb", torts_enabled: false },
    { name: "Carthage", type: "greek", torts_enabled: true },
    { name: "Cimmeria", type: "greek", torts_enabled: false },
    { name: "Colchis", type: "east", torts_enabled: false },
    { name: "Egypt", type: "greek", torts_enabled: false },
    { name: "Epirus", type: "greek", torts_enabled: true },
    { name: "Galatia", type: "barb", torts_enabled: false },
    { name: "Getae", type: "barb", torts_enabled: false },
    { name: "Iceni", type: "barb", torts_enabled: false },
    { name: "Kush", type: "barb", torts_enabled: false },
    { name: "Lusitani", type: "sally", torts_enabled: false },
    { name: "Macedon", type: "greek", torts_enabled: true },
    { name: "Masaesyli", type: "barb", torts_enabled: false },
    { name: "Massagetae", type: "sally", torts_enabled: false },
    { name: "Massilia", type: "greek", torts_enabled: false },
    { name: "Nabataea", type: "greek", torts_enabled: false },
    { name: "Nervii", type: "barb", torts_enabled: false },
    { name: "Odrysian Kingdom", type: "sally", torts_enabled: false },
    { name: "Parthia", type: "sally", torts_enabled: false },
    { name: "Pergamon", type: "greek", torts_enabled: false },
    { name: "Pontus", type: "greek", torts_enabled: false },
    { name: "Rome", type: "rome", torts_enabled: true },
    { name: "Roxolani", type: "sally", torts_enabled: false },
    { name: "Royal Schythia", type: "sally", torts_enabled: false },
    { name: "Saba", type: "sally", torts_enabled: false },
    { name: "Seleucid", type: "greek", torts_enabled: true },
    { name: "Sparta", type: "greek", torts_enabled: true },
    { name: "Suebi", type: "barb", torts_enabled: false },
    { name: "Syracuse", type: "greek", torts_enabled: false },
    { name: "Tylis", type: "barb", torts_enabled: false },
];
