import { Map } from "../types/matchupGeneratorTypes";
export const maps: Map[] = [
    { name: "Alexandria", type: "greek", requiresTorts: true },
    { name: "Alexandria Arachosia", type: "greek", requiresTorts: true },
    { name: "Ancyra", type: "barb", requiresTorts: false },
    { name: "Antioch", type: "greek", requiresTorts: true },
    { name: "Athens", type: "greek", requiresTorts: true },
    { name: "Babylon", type: "greek", requiresTorts: true },
    { name: "Brundisium", type: "greek", requiresTorts: true },
    { name: "Burdigala", type: "greek", requiresTorts: true },
    { name: "Camulodunon", type: "barb", requiresTorts: false },
    { name: "Carthago", type: "greek", requiresTorts: true },
    { name: "Casurgis", type: "greek", requiresTorts: true },
    { name: "Cyrene", type: "greek", requiresTorts: true },
    { name: "Delminium", type: "greek", requiresTorts: true },
    { name: "Diospolis", type: "greek", requiresTorts: true },
    { name: "Eildon", type: "barb", requiresTorts: false },
    { name: "Garama", type: "greek", requiresTorts: true },
    { name: "Gerrha", type: "greek", requiresTorts: true },
    { name: "Hecatompylos", type: "greek", requiresTorts: true },
    { name: "Kath", type: "greek", requiresTorts: true },
    { name: "Lupfurdum", type: "greek", requiresTorts: true },
    { name: "Massalia", type: "greek", requiresTorts: true },
    { name: "Medhlan", type: "barb", requiresTorts: false },
    { name: "Persepolis", type: "greek", requiresTorts: true },
    { name: "Petra", type: "greek", requiresTorts: true },
    { name: "Pulpudeva", type: "greek", requiresTorts: true },
    { name: "Roma", type: "greek", requiresTorts: true },
    { name: "Tarsus", type: "greek", requiresTorts: true },
    { name: "Thessalonike", type: "barb", requiresTorts: true },
    { name: "Tulifurdum", type: "barb", requiresTorts: false },
    { name: "Tur", type: "greek", requiresTorts: false },
    { name: "Zarmizegetusa", type: "greek", requiresTorts: true },
];